title: Portfolio
email: leo@leofavre.com
description: >
  Leonardo Favre’s portfolio.

# Build settings
markdown: kramdown

exclude:
  - package.json
  - node_modules/
  - rollup.config.js
  - resize-bitmaps.sh
  - npm-debug.log